# Generated by Django 5.2.8 on 2025-11-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referencias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('analisis_medico', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.medico')),
                ('paciente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tratamiento', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cie10_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referencias.cie10')),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presion_arterial', models.CharField(max_length=20)),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('saturacion_oxigeno', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historia_clinica.consulta')),
            ],
        ),
    ]
